# Generated by Django 6.1.1 on 2026-10-06 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0002_alter_entreprise_adresse_and_more'),
        ('ExpeditionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai_jours', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='ExpeditionApp.expedition')),
                ('transporteur', models.ForeignKey(limit_choices_to={'type_entreprise': 'transporteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='EntrepriseApp.entreprise')),
            ],
        ),
    ]
