# Generated by Django 6.1.1 on 2026-10-06 10:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntrepriseApp', '0002_alter_entreprise_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=11, unique=True)),
                ('capacite_kg', models.IntegerField(validators=[django.core.validators.MinValueValidator(100, 'Capacité doit etre sup à 100kg')])),
                ('disponibilite', models.BooleanField(default=True)),
                ('type_vehicule', models.CharField(choices=[('camionette', 'Camionette'), ('remorque', 'Semi-Remorque'), ('fourgon', 'Fourgon'), ('porteur', 'Porteur')], default='camionette', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='EntrepriseApp.entreprise')),
            ],
        ),
    ]
